# Generated by Django 4.1.4 on 2022-12-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project_data',
        ),
    ]
