# Generated by Django 4.1.4 on 2022-12-29 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='caption',
        ),
    ]
