# Generated by Django 4.1.4 on 2023-01-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0005_userblog_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
