# Generated by Django 4.1.4 on 2023-01-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0006_alter_profile_profile_pic_alter_userblog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profilepic'),
        ),
    ]
