# Generated by Django 4.1.4 on 2023-01-28 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0007_profile_email_profile_firstname_profile_lastname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userblog',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
