# Generated by Django 4.1.4 on 2023-01-28 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0010_rename_user_id_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
