# Generated by Django 4.1.4 on 2023-02-06 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newproject', '0011_alter_profile_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
        migrations.RenameField(
            model_name='userblog',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='profileimg'),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='image',
            field=models.ImageField(null=True, upload_to='blogimg'),
        ),
    ]
